export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR';
export const SET_QUERY_SEARCH = 'SET_QUERY_SEARCH';
export const SET_LOADING = 'SET_LOADING';
export const GET_NEWS = 'GET_NEWS';
export const ADD_TO_SAVED_NEWS = 'ADD_TO_SAVED_NEWS';

export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const CLEAR_CART = 'CLEAR_CART';
export const COUNT_CART_TOTALS = 'COUNT_CART_TOTALS';
